### ISSUE TITLE
训练报错

### ISSUE THREAD

**Issue by YankeesMolex** [breadcake/unsupervisedDeepHomography-pytorch#1]
请问博主使用的具体环境是什么呢？
我在使用pytorch=1.7使用预训练模型测试时一切正常，然而在训练时，出现了以下错误：RuntimeError: CUDA error: no kernel image is available for execution on the device
但是我的这个虚拟环境经过测试是可以正常训练Deep Homography Estimation代码的

**Comment by breadcake** [comment]
你好，我使用的环境是cuda10.0 pytorch1.2.0，你可以试下这个版本。
另外我只是简单地训练了，没怎么调参，理论上模型精度可以更高。

**Comment by YankeesMolex** [comment]
> 你好，我使用的环境是cuda10.0 pytorch1.2.0，你可以试下这个版本。 另外我只是简单地训练了，没怎么调参，理论上模型精度可以更高。

哦哦，好的！感谢校友哈~
